"""
Django settings for wayrem project.
Generated by 'django-admin startproject' using Django 3.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.contrib.messages import constants as messages_s
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)(85bhh^@-x_8cpzbvc7*z9&$*c8#l&3uimsl+odf2ub&h3r2&'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ckeditor',
    'wayrem_admin',
    'wayrem_admin.users',
    'widget_tweaks',
    'maintenance_mode',
    'django_celery_beat',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wayrem_admin.middlewares.notification_middleware.NotificationMiddleWare',
    "maintenance_mode.middleware.MaintenanceModeMiddleware",

]


ROOT_URLCONF = 'wayrem.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wayrem_admin.users.context_processors.show_menu',
                'wayrem_admin.context_processors.admin_media',
            ],
            'libraries': {
                'util_tags': 'wayrem_admin.templatetags.util_tags',
            }
        },
    },
]
WSGI_APPLICATION = 'wayrem.wsgi.application'
# WSGI_APPLICATION = 'wsgi.application'
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wayrem_stg_v2',
        'USER': 'wayremdb_adminuser',
        'PASSWORD': 'r2wXJfUs78NczMFWRXcV',
        'HOST': 'db',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
            "init_command": "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
        },
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wayrem_stg_v2',
#         'USER': 'root',
#         'PASSWORD': 'root1234',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             "init_command": "SET foreign_key_checks = 0;",
#             "init_command": "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
#         },
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wayrem_v8_test',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             "init_command": "SET foreign_key_checks = 0;",
#             "init_command": "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
#         },
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kuwait'
USE_I18N = True
USE_L10N = True
USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#AUTH_USER_MODEL = 'wayrem_admin.User'
#AUTH_USER_MODEL = 'wayrem_admin.User'
AUTH_USER_MODEL = 'wayrem_admin.Users'
AUTHENTICATION_BACKENDS = ('wayrem_admin.users.backends.MyAuthBackend',)


MESSAGE_TAGS = {messages_s.ERROR: 'danger'}
# ! Media Files Local settings
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'
# ! Media Files Server settings
# MEDIA_ROOT = os.path.dirname(
#     "/opt/app/wayrem-admin-backend/media/common_folder/")
MEDIA_ROOT = os.path.join(os.path.abspath("."), "media", "common_folder")
MEDIA_URL = '/media/common_folder/'


# MEDIA_ROOT = os.path.dirname(
#     "/home/fealty/Desktop/admin_dev_8/wayrem-admin-backend/media/common_folder/")
# MEDIA_URL = '/media/'
# /home/suryaaa/Music/database/

####################################
##  CKEDITOR CONFIGURATION ##
####################################
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
CKEDITOR_UPLOAD_PATH = 'uploads/help/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom':  [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['TextColor', 'BGColor'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['Link', 'Unlink'], ['JustifyLeft', 'JustifyCenter',
                                 'JustifyRight', 'JustifyBlock'],
            ['NumberedList', 'BulletedList', 'Image', 'HorizontalRule', '-', 'RemoveFormat'], [
                'Outdent', 'Indent', 'Blockquote', 'CreateDiv', 'Table', 'SpecialChar', 'PageBreak'],
            ['Preview', 'Maximize', 'Source']
        ],
        'toolbarLocation': 'bottom',
        'height': 200,
        'width': '100%',
        'removePlugins': 'elementspath',
        'extraPlugins': 'image2,uploadimage'
    },
    'reply_ckeditor': {
        'toolbar': 'Custom',
        'toolbar_Custom':  [
            ['Bold', 'Italic', 'Underline'],
            ['TextColor', 'BGColor'],
            ['Font', 'FontSize'],
            ['Link', 'Unlink'], ['JustifyLeft', 'JustifyCenter',
                                 'JustifyRight', 'JustifyBlock'],
            ['NumberedList', 'BulletedList', 'Image', '-',
                'Blockquote', 'Table', 'SpecialChar'],
            ['Maximize']
        ],
        'toolbarLocation': 'bottom',
        'height': 230,
        'width': 'auto',
        'width': '100%',
        'removePlugins': 'elementspath',
        'extraPlugins': 'image2,uploadimage'
    },
}
# MAINTENANCE_MODE = True
# MAINTENANCE_MODE_IGNORE_IP_ADDRESSES = ("49.36.40.132")

FLAG_SSL = True
LOGIN_URL = '/'
BASE_URL = 'http://localhost:8000'
# celery
CELERY_BROKER_URL = 'redis://redis-server:6379'
CELERY_RESULT_BACKEND = 'redis://redis-server:6379'

# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

# redis server
# redis-server
# celery server
#  celery -A wayrem.celery worker --loglevel=info
# celery beat server
# celery -A wayrem beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
#CORS_ORIGIN_WHITELIST = ( '15.185.103.226','52.77.99.245','13.228.17.195','18.136.241.16','3.1.127.224','52.76.48.59', )
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
