# Generated by Django 3.2.7 on 2021-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayrem_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
