from wayrem_admin.views.auth import *
from wayrem_admin.views.account import *
from wayrem_admin.views.category import *
from wayrem_admin.views.subcategory import *
from wayrem_admin.views.home import *
from wayrem_admin.views.invoice import *
from wayrem_admin.views.ingredients import *
from wayrem_admin.views.product import *
from wayrem_admin.views.purchase_order import *
from wayrem_admin.views.roles import *
from wayrem_admin.views.supplier import *
from wayrem_admin.views.setting import *
from wayrem_admin.views.customer import *
from wayrem_admin.views.emailtemplates import *
from wayrem_admin.views.orders import *
