RECORDS_PER_PAGE = 25
CURRENCY = "SAR"
CURRENCY_KEY = "currency_key"
ORDER_STATUS = 4

ORDER_PENDING_APPROVED = 16
ORDER_APPROVED = 17
ORDER_CANCELLED = 18
OREDER_PENDING_RECURENCE = 23

ORDER_STATUS_RECEIVED = 1   # delivery status
ORDER_STATUS_PREPARING = 2
ORDER_STATUS_DELIVERING = 4  # delivery status
ORDER_STATUS_CANCELLED = 15  # delivery status


ORDER_DELIVERY_PICKUP = 3
ORDER_DELIVERING = 4
ORDER_DELIVERY_ATTEMPTED_PICKUP = 19
ORDER_DELIVERY_DELIVERED = 5
ORDER_DELIVERY_PARTIALLY_DELIVERED = 20
ORDER_DELIVERY_ATTEMPTED_DELIVERED = 21
ORDER_RETURNED_WAREHOUSE = 22
ORDER_DELIVERY_CANCELLED = 15

INVENTORY_ORDER_STATUS_ORDERED = 'ordered'
INVENTORY_ORDER_STATUS_SHIPPED = 'shipped'
INVENTORY_ORDER_STATUS_CANCELLED = 'cancelled'

PAYMENT_STATUS = 2
PAYMENT_MODE = 3
PAYMENT_STATUS_PENDING = 6
PAYMENT_STATUS_PENDING_APPROVAL=27
PAYMENT_STATUS_PARTIAL_PAYMENT=31
PAYMENT_STATUS_CONFIRM = 7
PAYMENT_STATUS_DECLINED = 8
PAYMENT_STATUS_REJECTED=26
BANKTRANSFER_MODE = 12
CREDIT_MODE=13

FORECAST_PRODUCT_THRESHOLD = 'forecast_product_threshold'
DELIVERY_SPAN = 'forecast_delivery_span_per_day'
FORECAST_DEFAULT_VALUE = 3
FORECAST_PREVIOUS_RECORD_DELETE = 15

# Loginext

LOGINEXT_USERNAME = 'loginext_username'
LOGINEXT_PASSWORD = 'loginext_password'
LOGINEXT_BASEPATH = 'loginext_basepath'

DELIVERY_ORDER_PER_DAY = 'delivery_order_per_day'
CUSTOMER_APPROVAL_PER_DAY = 'customer_approved_per_day'

SETTING_VAT = 'setting_vat'
DEFAULT_SHIPPING_AMOUNT = 10
PRODUCT_MARGIN_PERC_UNIT = "%"

INVOICE_DEFAULT = 1001
FREE_SHIPPING_TOTAL = 500
PAID_SHIPPING_CHARGE = 'delivery_order_recurrent_fixcharge'

BUSINESS_TYPE_ID = 5
ORDER_PAYMENT_PENDING=28
COD=10
ORDER_TYPE_DRAFT=29
ORDER_TYPE_ONLINE_CUSTOMERS=24