RECORDS_PER_PAGE=25
CURRENCY="SAR"
CURRENCY_KEY="currency_key"
ORDER_STATUS=1
ORDER_STATUS_RECEIVED=1
ORDER_STATUS_DELIVERING=4
ORDER_STATUS_Cancelled=15

INVENTORY_ORDER_STATUS_ORDERED='ordered'
INVENTORY_ORDER_STATUS_SHIPPED='shipped'
INVENTORY_ORDER_STATUS_CANCELLED='cancelled'

PAYMENT_STATUS=2
PAYMENT_MODE=3
PAYMENT_STATUS_CONFIRM=7
PAYMENT_STATUS_DECLINED=8


FORECAST_PRODUCT_THRESHOLD = 'forecast_product_threshold'
DELIVERY_SPAN='forecast_delivery_span_per_day'
FORECAST_DEFAULT_VALUE=3
FORECAST_PREVIOUS_RECORD_DELETE=15